const product_card = [
  {
    id: 1,
    product_name: "Small dress",
    description: "Wide dress and stripes",
    price: 350,
    currency: "$",
    thumb: "/photo/image1.png",
  },
  {
    id: 2,
    product_name: "Black dress?",
    description: "Wide dress and stripes",
    price: 350,
    currency: "$",
    thumb: "/photo/image2.png",
  },
  {
    id: 3,
    product_name: "Blue long dress",
    description: "long dress and stripes",
    price: 350,
    currency: "$",
    thumb: "/Photo/image3.png",
  },
  {
    id: 4,
    product_name: "Black small dress",
    description: "Wide dress and red",
    price: 350,
    currency: "$",
    thumb: "/Photo/image5.png",
  },
  {
    id: 5,
    product_name: "Black small dress",
    description: "Wide dress and red",
    price: 350,
    currency: "$",
    thumb: "/Photo/image5.png",
  },
  {
    id: 6,
    product_name: "Blue long dress",
    description: "Wide dress and red",
    price: 350,
    currency: "$",
    thumb: "/Photo/image3.png",
  },
  {
    id: 7,
    product_name: "Black small dress",
    description: "Wide dress and red",
    price: 350,
    currency: "$",
    thumb: "/photo/image1.png",
  },
  {
    id: 8,
    product_name: "Black small dress",
    description: "Wide dress and red",
    price: 350,
    currency: "$",
    thumb: "/Photo/image5.png",
  },
  {
    id: 9,
    product_name: "Black dress?",
    description: "Wide dress and red",
    price: 350,
    currency: "$",
    thumb: "/photo/image2.png",
  },
];

export default product_card;
